.\" man page create by R# package system.
.TH CFD 1 2000-Jan "dump_stream" "dump_stream"
.SH NAME
dump_stream \- 
.SH SYNOPSIS
\fIdump_stream(\fBpack\fR as <generic> FrameReader, 
\fBfs\fR as any, 
\fBdimension\fR as string = "speed2", 
\fBcolors\fR as any = "viridis", 
\fBcolor_levels\fR as integer = 200, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
CFD
.SH FILES
.PP
CFD_clr.dll
.PP
