.\" man page create by R# package system.
.TH CFD 1 2000-Jan "open.pack" "open.pack"
.SH NAME
open.pack \- open the CFD frame data matrix storage
.SH SYNOPSIS
\fIopen.pack(\fBfile\fR as any, 
\fBmode\fR as <integer> FileAccess = [Read], 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
open the CFD frame data matrix storage
.PP
.SH OPTIONS
.PP
\fBfile\fB \fR\- -. 
.PP
.PP
\fBmode\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
CFD
.SH FILES
.PP
CFD_clr.dll
.PP
