.\" man page create by R# package system.
.TH CFD 1 2000-Jan "session" "session"
.SH NAME
session \- Create a new CFD session
.SH SYNOPSIS
\fIsession(\fBstorage\fR as <generic> FrameWriter, 
\fBdims\fR as any = "1920,1080", 
\fBinterval\fR as integer = 30, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Create a new CFD session
.PP
.SH SEE ALSO
CFD
.SH FILES
.PP
CFD_clr.dll
.PP
