'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports RibbonLib
Imports RibbonLib.Controls

Namespace RibbonLib.Controls
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdTabPage As UInteger = 3
            Public Const cmdCommandGroup As UInteger = 4
            Public Const cmdFileOpen As UInteger = 8
            Public Const cmdButtonReset As UInteger = 2
            Public Const cmdButtonClearBarrier As UInteger = 6
            Public Const cmdCheckDrawBarrier As UInteger = 7
            Public Const cmdMenu2 As UInteger = 10
            Public Const cmdCheckShowTracer As UInteger = 9
            Public Const cmdCheckShowFlowLine As UInteger = 11
        End Class

        ' ContextPopup CommandName

        Private _ribbon As Ribbon
        Public ReadOnly Property Ribbon As Ribbon
            Get
                Return _ribbon
            End Get
        End Property
        Private _TabPage As RibbonTab
        Public ReadOnly Property TabPage As RibbonTab
            Get
                Return _TabPage
            End Get
        End Property
        Private _CommandGroup As RibbonGroup
        Public ReadOnly Property CommandGroup As RibbonGroup
            Get
                Return _CommandGroup
            End Get
        End Property
        Private _FileOpen As RibbonButton
        Public ReadOnly Property FileOpen As RibbonButton
            Get
                Return _FileOpen
            End Get
        End Property
        Private _ButtonReset As RibbonButton
        Public ReadOnly Property ButtonReset As RibbonButton
            Get
                Return _ButtonReset
            End Get
        End Property
        Private _ButtonClearBarrier As RibbonButton
        Public ReadOnly Property ButtonClearBarrier As RibbonButton
            Get
                Return _ButtonClearBarrier
            End Get
        End Property
        Private _CheckDrawBarrier As RibbonToggleButton
        Public ReadOnly Property CheckDrawBarrier As RibbonToggleButton
            Get
                Return _CheckDrawBarrier
            End Get
        End Property
        Private _Menu2 As RibbonGroup
        Public ReadOnly Property Menu2 As RibbonGroup
            Get
                Return _Menu2
            End Get
        End Property
        Private _CheckShowTracer As RibbonToggleButton
        Public ReadOnly Property CheckShowTracer As RibbonToggleButton
            Get
                Return _CheckShowTracer
            End Get
        End Property
        Private _CheckShowFlowLine As RibbonToggleButton
        Public ReadOnly Property CheckShowFlowLine As RibbonToggleButton
            Get
                Return _CheckShowFlowLine
            End Get
        End Property

        Public Sub New(ByVal ribbon As Ribbon)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _TabPage = New RibbonTab(_ribbon, Cmd.cmdTabPage)
            _CommandGroup = New RibbonGroup(_ribbon, Cmd.cmdCommandGroup)
            _FileOpen = New RibbonButton(_ribbon, Cmd.cmdFileOpen)
            _ButtonReset = New RibbonButton(_ribbon, Cmd.cmdButtonReset)
            _ButtonClearBarrier = New RibbonButton(_ribbon, Cmd.cmdButtonClearBarrier)
            _CheckDrawBarrier = New RibbonToggleButton(_ribbon, Cmd.cmdCheckDrawBarrier)
            _Menu2 = New RibbonGroup(_ribbon, Cmd.cmdMenu2)
            _CheckShowTracer = New RibbonToggleButton(_ribbon, Cmd.cmdCheckShowTracer)
            _CheckShowFlowLine = New RibbonToggleButton(_ribbon, Cmd.cmdCheckShowFlowLine)
        End Sub

    End Class
End Namespace
