.\" man page create by R# package system.
.TH TCP 1 2000-Jan "start" "start"
.SH NAME
start \- start the backend service
.SH SYNOPSIS
\fIstart(\fBdebug_port\fR as <generic> Int32 = \fB<NULL>\fR, 
\fBmodel_file\fR as string = \fB<NULL>\fR, 
\fBsession_file\fR as string = \fB<NULL>\fR);\fR
.SH DESCRIPTION
.PP
start the backend service
.PP
.SH DETAILS
.PP
the server thread will be blocked at here
.PP
.SH SEE ALSO
Tcp
.SH FILES
.PP
CFD_clr.dll
.PP
